### ISSUE TITLE
Trouble with latest release 

### ISSUE THREAD

**Issue by gjosang** [mhum/pia-transmission-updater#8]
Hi, 

Having some problems with the new version.. 
Getting the following error: 

key "port-is-open" not known in dictionary
    while executing
"dict get [dict get $resp_data arguments] port-is-open"
    (procedure "_isPortOpen" line 16)
    invoked from within
"_isPortOpen"
    (procedure "_checkPort" line 3)
    invoked from within
"_checkPort"
    (procedure "::upd::updTransmission::checkPort" line 3)
    invoked from within
"::upd::updTransmission::checkPort"
    (file "./updater.tcl" line 16)

**Output from debug:**
DEBUG: Connecting to transmission at: http://localhost:9091/transmission/rpc
DEBUG: Send request to Transmission
DEBUG: Query:
DEBUG: Headers: Authorization {Basic dHJhbnNtaXNzaW9uOnRyYW5zbWlzc2lvbg==}
DEBUG: Response:
DEBUG: Server Transmission X-Transmission-Session-Id Al2EGbHspdRMZDnItavovXHcDheRWbl4UXMd3UgqfAzrRuNY Date {Tue, 30 Aug 2016 17:47:24 GMT} Content-Length 580 Content-Type {text/html; charset=ISO-8859-1} Connection close
DEBUG: Retrieved CSRF token: Al2EGbHspdRMZDnItavovXHcDheRWbl4UXMd3UgqfAzrRuNY
DEBUG: Set headers: Authorization {Basic dHJhbnNtaXNzaW9uOnRyYW5zbWlzc2lvbg==} X-Transmission-Session-Id Al2EGbHspdRMZDnItavovXHcDheRWbl4UXMd3UgqfAzrRuNY
DEBUG: Send request to Transmission
DEBUG: Query: {"arguments": {},"method": "port-test"}
DEBUG: Headers: Authorization {Basic dHJhbnNtaXNzaW9uOnRyYW5zbWlzc2lvbg==} X-Transmission-Session-Id Al2EGbHspdRMZDnItavovXHcDheRWbl4UXMd3UgqfAzrRuNY
DEBUG: Response:
DEBUG: arguments {} result {portTested: http error 0: No Response}
DEBUG: Received: arguments {} result {portTested: http error 0: No Response}
key "port-is-open" not known in dictionary
    while executing
"dict get [dict get $resp_data arguments] port-is-open"
    (procedure "_isPortOpen" line 16)
    invoked from within
"_isPortOpen"
    (procedure "_checkPort" line 3)
    invoked from within
"_checkPort"
    (procedure "::upd::updTransmission::checkPort" line 3)
    invoked from within
"::upd::updTransmission::checkPort"
    (file "./updater.tcl" line 16)

Do you have any ideas?

**Comment by mhum** [comment]
Hi @gjosang,

I think this is due to a crazy coincidence! I'm sure as you saw when you ran the script, it sits there for a while waiting for Transmission to respond to the port check. It also seems the port checking functionality with the Transmission web application is also not working. I'm not completely certain how Transmission has implemented it's port checking, but I'm assuming it's using some service from the Transmission website. The Transmission website is currently not responding (https://www.transmissionbt.com) which I think is the reason why the port checking isn't working.

I've released a new version that will go ahead and update the port in Transmission anyways if the port check call fails for some reason. I've also added a new config in which you can skip the port checking. You can either add `check_port 0` to your config file or pass `--check_port 0` from the command line.

**Comment by gjosang** [comment]
I see. Thats explains alot. I have a manual script that can fetch a new port, and transmission reported that to be closed also. 

I'am still seeing this error: 
WARNING: Something went wrong with Transmission port check:
portTested: http error 0: No Response
WARNING: Updating Transmission port regardless....
Port is no longer open. Let's continue!
key "port" not known in dictionary
    while executing
"dict get $resp port"
    (procedure "::upd::updPia::fetchPort" line 49)
    invoked from within
"::upd::updPia::fetchPort"
    invoked from within
"set port [::upd::updPia::fetchPort]"
    (file "./updater.tcl" line 19)

I'am running on ubuntu 14.04 and tcl8.6

**Comment by mhum** [comment]
Is there anything interesting when you run it with the debug flag? It seems the response back from PIA with the port is not in the expected format. One of the recent features I added was to make the request to PIA over TLS if the PIA address began with `https`.

**Comment by gjosang** [comment]
I removed the .pia_client_id and generated a new. That worked.. 
Weird.. well I'am happy :-) 

Keep up the good work! These script has made my life alot easier 👍

**Comment by mhum** [comment]
Strange. Glad that worked for you! Great to know that someone else is finding this useful too!
